### ISSUE TITLE
Issue when creating small blends - RuntimeError: Nothing to blend

### ISSUE THREAD

**Issue by bloughran618** [desResLab/feMorph#1]
This is Brian Loughran from CSE Methods at PW. I am using the femorph_blender package as a piece of an automated blend disposition workflow at Pratt and I was having an issue with the femorph blender python package. The issue is when creating small blends (e.g. blend_depth ~= 0.025") I get the following error:

`RuntimeError: Nothing to blend.  Blend geometry may be invalid.`

Running geometry with the same proportions greater than ~0.025” blend depth has produced a valid geometry and successfully blended, which is why the error message for the small blends is odd. 

I initially tried to do a mesh refinement in the area of the blend, suspecting that it was just a mesh morphing problem, however that was unsuccessful. This seems to be unrelated to the mesh of the model. Is this intended behavior of the tool? Or is this a potential bug? I would appreciate any experience that could be shared.

I am using the following code for blend creation:

```
from femorph_blender import Blender

fem = Blender("30g2306_femorph_a15_rev4.cdb")
fem.define_edge("LENODE1")
fem.blend_on_edge(0.095, 0.03, 0.02, 0, 0, 2)
```

This corresponds to the following blend definition:

```
blend_def = {
        "fillet_radius": 0,
        "blend_depth": 0.015,
        "blend_length": 0.06,
        "flat_length": 0,
        "prop_factor": 2,
        "span_loc": 0.15
}
```

For reference, the model that I am using has been uploaded via MFT under folder AFRL-FEMORPH-HTTPS-US -> FromPW with file name 30g2306_femorph_a15_rev4.cdb.

**Comment by daneschi** [comment]
It looks like the wrong repo. 
This code has nothing do to with Blender.
